/* ===== ESTADO ===== */
const ST={g(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},s(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
let S={bag:ST.g("tb",[]),fav:ST.g("tf",[]),cp:null,user:ST.g("tu",null),step:0,ck:{},ship:0,pay:"pix",V:{tam:null,cor:null,q:1,img:0},F:{}};
const $=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
const brl=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const inst=p=>`ou ${CFG.inst}x de ${brl(p*(1+CFG.card)/CFG.inst)} no cartão`;
const dr=c=>{document.body.classList.remove("m","g");c&&document.body.classList.add(c)};
const by=id=>PRODS.find(p=>p.id==id);
const save=()=>{ST.s("tb",S.bag);ST.s("tf",S.fav);ST.s("tu",S.user)};
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("on");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("on"),2200)};
/* ===== COMPONENTES ===== */
const ph=(p,i)=>{const c=p.cores[i%p.cores.length]||"g",a=CL[c][1],z=["#DDD6CA","#CFC6B8","#B9AE9E","#E7E0D3"][(p.id+i)%4];
return `<div class="ph" style="--a:${a};--z:${z};--d:${140+i*35}deg" role="img" aria-label="${p.nome}, foto ${i+1}">${p.img[0]&&i<3?`<img loading="lazy" decoding="async" src="${p.img[0]}" alt="${p.nome}, foto ${i+1}" style="${["","transform:scale(1.6);transform-origin:68% 22%","transform:scale(1.6);transform-origin:68% 78%"][i]}">`:`<span>${p.nome}</span>`}</div>`};
const tile=(t,href,i,pid)=>{const src=pid=="brand"?IMGS.brand:pid=="cover"?IMGS.cover:pid&&(by(pid)||{img:[]}).img[0];return `<a class="tile" href="${href}"><div class="ph" style="--a:#CFC6B8;--z:#8F8577">${src?`<img loading="lazy" src="${src}" alt="${t||"Tramisse"}">`:""}</div><em>${t}</em></a>`};
const fh=id=>`<button class="fav" data-fav="${id}" aria-pressed="${S.fav.includes(id)}" aria-label="Favoritar"><svg viewBox="0 0 24 24"><path d="M12 20s-8-5-8-11a4.5 4.5 0 018-2.8A4.5 4.5 0 0120 9c0 6-8 11-8 11z"/></svg></button>`;
const card=p=>`<article class="card">${p.de?`<span class="tag">-${Math.round((1-p.preco/p.de)*100)}%</span>`:p.flags.includes("N")?'<span class="tag">NEW IN</span>':""}${fh(p.id)}<a class="im" href="#/p/${p.slug}">${ph(p,0)}<div class="h">${ph(p,1)}</div></a><div class="sw">${p.cores.map(c=>`<i style="background:${CL[c][1]}" title="${CL[c][0]}"></i>`).join("")}</div><a class="n" href="#/p/${p.slug}">${p.nome}</a><b>${p.de?`<s>${brl(p.de)}</s>`:""}${brl(p.preco)}</b><small>${inst(p.preco)}</small></article>`;
const carousel=(list,id)=>`<div class="car" id="${id}">${list.map(card).join("")}</div>`;
const reel=v=>{const p=by(v.pid);return `<a class="reel" href="#/p/${p.slug}">${v.src?`<video src="${v.src}" poster="${p.img[0]}" muted loop playsinline preload="none" data-rv></video>`:`<img class="kb" loading="lazy" src="${p.img[0]}" alt="${p.nome}">`}<span>${p.nome.toUpperCase()}</span></a>`};
const vio=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting?e.target.play().catch(()=>{}):e.target.pause()),{threshold:.5});
const cbtn=id=>`<div class="cb"><button data-car="${id}" data-d="-1" aria-label="Anterior">‹</button><button data-car="${id}" data-d="1" aria-label="Próximo">›</button></div>`;
/* ===== SHELL ===== */
function shell(){
$("#top").innerHTML=CFG.top.map(t=>`<span>${t}</span>`).join("");
const main=[["NEW IN","#/c/new-in"],["CURADORIA ESPECIAL","#/c/curadoria"]];
const dd=(k,l)=>`<div class="dd"><a href="#/c/${k}">${l}</a><div class="sub">${Object.entries(TREE[k]).map(([g,a])=>`<div><b>${g.toUpperCase()}</b>${a.map(s=>`<a href="#/c/${k}/${slug(s)}">${s}</a>`).join("")}<a href="#/c/${k}">Ver tudo</a></div>`).join("")}</div></div>`;
$("#pri").innerHTML=main.map(([l,h])=>`<div><a href="${h}">${l}</a></div>`).join("")+dd("roupas","ROUPAS")+dd("acessorios","ACESSÓRIOS")+`<div><a href="#/c/sale">SALE</a></div>`;
const md=(k,l)=>`<details><summary>${l}</summary>${Object.entries(TREE[k]).map(([g,a])=>(k=="roupas"?`<small>${g.toUpperCase()}</small>`:"")+a.map(s=>`<a href="#/c/${k}/${slug(s)}">${s}</a>`).join("")).join("")}<a href="#/c/${k}">Ver tudo</a></details>`;
$("#menu").innerHTML=`<div class="dh"><h2>Menu</h2><button class="b" data-a="close" aria-label="Fechar">✕</button></div><div class="ml"><a href="#/c/new-in">NEW IN</a><a href="#/c/curadoria">CURADORIA ESPECIAL</a>${md("roupas","ROUPAS")}${md("acessorios","ACESSÓRIOS")}<a href="#/c/sale">SALE</a><a href="#/conta">MINHA CONTA</a><a href="#/favoritos">FAVORITOS</a><a href="#/pagina/contato">FALE CONOSCO</a></div>`;
const L=(t,h)=>`<a href="${h}">${t}</a>`;
$("#ft").innerHTML=`<div><a class="logo" href="#/" style="color:var(--ink)">TRAMISSE</a><p style="color:var(--mut)">Essencial. Atemporal. Tramisse.</p></div>
<div><h3>TRAMISSE</h3>${L("Sobre nós","#/sobre")}${L("Nossa história","#/sobre")}${L("Contato","#/pagina/contato")}</div>
<div><h3>SHOP</h3>${L("New In","#/c/new-in")}${L("Curadoria Especial","#/c/curadoria")}${L("Roupas","#/c/roupas")}${L("Acessórios","#/c/acessorios")}${L("Sale","#/c/sale")}</div>
<div><h3>ATENDIMENTO</h3>${L("Trocas e devoluções","#/pagina/trocas")}${L("Entrega","#/pagina/trocas")}${L("Formas de pagamento","#/pagina/faq")}${L("FAQ","#/pagina/faq")}${L("Guia de tamanhos","#/pagina/faq")}${L("Privacidade","#/pagina/privacidade")}${L("Termos de uso","#/pagina/termos")}</div>
<div><h3>SIGA A TRAMISSE</h3>${CFG.social.map(s=>`<a href="${s[1]||"#/"}"${s[1]?' target="_blank" rel="noopener"':""}>${s[0]}</a>`).join("")}</div>`;
counts()}
function counts(){const nb=S.bag.reduce((a,l)=>a+l.q,0);$("#nb").textContent=nb;$("#nb").style.display=nb?"":"none";$("#nf").textContent=S.fav.length;$("#nf").style.display=S.fav.length?"":"none"}
/* ===== SACOLA ===== */
const tot=()=>{const sub=S.bag.reduce((a,l)=>a+l.q*by(l.id).preco,0),d=S.cp?sub*CFG.coupons[S.cp]:0,acr=S.step>=3&&S.pay!="pix"?(sub-d)*CFG.card:0;return{sub,d,acr}};
function bag(){const t=tot();
$("#bag").innerHTML=`<div class="dh"><h2>Sacola (${S.bag.reduce((a,l)=>a+l.q,0)})</h2><button class="b" data-a="close" aria-label="Fechar">✕</button></div>
${S.bag.length?`<div style="flex:1">${S.bag.map((l,i)=>{const p=by(l.id);return `<div class="ln"><div class="im">${ph(p,0)}</div><div><a href="#/p/${p.slug}">${p.nome}</a><br><small>${CL[l.cor][0]} · ${l.tam}</small><br>${brl(p.preco)}<div style="margin-top:8px"><span class="qty"><button data-q="${i}" data-d="-1" aria-label="Diminuir">−</button><span>${l.q}</span><button data-q="${i}" data-d="1" aria-label="Aumentar">+</button></span><button class="r" data-rm="${i}">Remover</button></div></div></div>`}).join("")}</div>
<p style="text-align:center;font-size:13px;color:var(--mut);margin:16px 0 0">Entrega por aplicativo: o valor é informado na compra.</p>
<div class="cp"><input id="cpi" placeholder="Código de desconto" aria-label="Código de desconto"><button class="btn o" data-a="coupon" style="padding:0 20px">OK</button></div><div class="er" id="cpe">${S.cp?`<span class="okk">Cupom ${S.cp} aplicado.</span>`:""}</div>
<div class="tt"><span>Subtotal</span><span>${brl(t.sub)}</span></div><div class="tt"><span>Entrega</span><span>Por aplicativo</span></div>${t.d?`<div class="tt"><span>Desconto</span><span>-${brl(t.d)}</span></div>`:""}<div class="tt big"><span>Total</span><span>${brl(t.sub-t.d)}</span></div>
<a class="btn f" href="#/checkout" style="margin-top:16px" data-a="close">FINALIZAR COMPRA</a><button class="btn o f" data-a="close" style="margin-top:8px;border:0">CONTINUAR COMPRANDO</button>`:`<p style="flex:1;color:var(--mut)">Sua sacola está vazia.</p><a class="btn f" href="#/c/new-in" data-a="close">VER NEW IN</a>`}`;counts()}
/* ===== VIEWS ===== */
const V={};
V.home=()=>{const n=PRODS.filter(p=>p.flags.includes("N")),b=PRODS.filter(p=>p.flags.includes("B"));const H=CFG.hero;
return `<section class="hero" aria-label="Campanha"><div class="ph" style="--a:#B9AE9E;--z:#6E665B;--d:160deg">${H.desktop?`<picture><source media="(max-width:700px)" srcset="${H.mobile||H.desktop}"><img src="${H.desktop}" alt="Campanha Tramisse"></picture>`:""}</div><div class="in"><h1 class="logo big">TRAMISSE</h1><p>ESSENCIAL. ATEMPORAL.</p><a class="btn" href="#/c/new-in">COMPRAR AGORA</a></div></section>
<section class="sec"><div class="w"><div class="tiles">${[["NEW IN","#/c/new-in"],["CURADORIA ESPECIAL","#/c/curadoria"],["ROUPAS","#/c/roupas"],["ACESSÓRIOS","#/c/acessorios"]].map((t,i)=>tile(t[0],t[1],i,TP[t[0]])).join("")}</div></div></section>
<section class="sec" style="padding-top:0"><div class="w"><div class="sh"><div><h2>NEW IN</h2><p>Novidades que chegam para fazer parte da sua história.</p></div>${cbtn("c1")}</div>${carousel(n,"c1")}<p style="text-align:center;margin-top:40px"><a class="btn o" href="#/c/new-in">VER TODAS</a></p></div></section>
<section class="cur"><h2>Curadoria Especial</h2><p>Uma seleção especial de peças escolhidas para traduzir a essência da Tramisse.</p><a class="btn" href="#/c/curadoria">EXPLORAR CURADORIA</a></section>
<section class="sec"><div class="w"><div class="sh"><div><h2>Em movimento</h2><p>Os looks da Tramisse ganhando vida.</p></div>${cbtn("c3")}</div><div class="car reels" id="c3">${CFG.videos.map(reel).join("")}</div></div></section>
<section class="sec" style="padding-top:0"><div class="w"><div class="sh"><h2>Compre por categoria</h2></div><div class="tiles six">${["Blusas","Calças","Vestidos","Conjuntos","Saias","Macacões"].map((t,i)=>tile(t.toUpperCase(),`#/c/roupas/${slug(t)}`,i+2,TP[t.toUpperCase()])).join("")}</div></div></section>
<section class="sec" style="padding-top:0"><div class="w"><div class="sh"><h2>Compre por estilo</h2></div><div class="tiles st">${["Casual","Office","Night","Weekend"].map((t,i)=>tile(t.toUpperCase(),`#/c/estilo/${slug(t)}`,i+1,TP[t.toUpperCase()])).join("")}</div></div></section>
<section class="sec" style="padding-top:0"><div class="w"><div class="sh"><h2>As mais desejadas</h2>${cbtn("c2")}</div>${carousel(b,"c2")}<p style="text-align:center;margin-top:40px"><a class="btn o" href="#/c/todos">VER TODOS</a></p></div></section>
<section class="nl"><h2>Fique por perto</h2><p style="color:var(--mut)">Receba novidades, lançamentos e conteúdos da Tramisse.</p><form data-form="nl"><input type="email" name="e" placeholder="Seu melhor e-mail" aria-label="Seu melhor e-mail" required><button class="btn">CADASTRAR</button></form><div class="er" id="nle"></div></section>`};
const INFO={"new-in":["New In","Novidades que chegam para fazer parte da sua história."],curadoria:["Curadoria Especial","Uma seleção especial de peças escolhidas para traduzir a essência da Tramisse."],roupas:["Roupas","Peças essenciais, de modelagem precisa e caimento atemporal."],acessorios:["Acessórios","Os detalhes que assinam o look."],sale:["Sale","Peças da Tramisse com condições especiais."],todos:["Ver tudo","Toda a coleção Tramisse."],estilo:["Estilo","Uma seleção pensada para cada momento."]};
function list(k,sub){let l=PRODS;if(k=="new-in")l=l.filter(p=>p.flags.includes("N"));else if(k=="curadoria")l=l.filter(p=>p.flags.includes("K"));else if(k=="sale")l=l.filter(p=>p.de);else if(k=="estilo")l=l.filter(p=>slug(p.estilo)==sub);else if(k!="todos")l=l.filter(p=>p.cat==k&&(!sub||slug(p.sub)==sub));
const F=S.F;if(F.tam)l=l.filter(p=>p.tam.includes(F.tam));if(F.cor)l=l.filter(p=>p.cores.includes(F.cor));if(F.pr){const[a,b]=F.pr.split("-");l=l.filter(p=>p.preco>=+a&&p.preco<=+b)}if(F.col)l=l.filter(p=>p.col==F.col);if(F.est)l=l.filter(p=>p.estilo==F.est);if(F.disp)l=l.filter(p=>Object.values(p.est).some(x=>x>0));
const o=F.o||"n";return [...l].sort((a,b)=>o=="lo"?a.preco-b.preco:o=="hi"?b.preco-a.preco:o=="b"?(b.flags.includes("B")-a.flags.includes("B")):b.id-a.id)}
V.cat=(k,sub)=>{const I=INFO[k]||INFO.todos,F=S.F,sel=(n,l,o)=>`<select data-f="${n}" aria-label="${l}"><option value="">${l}</option>${o.map(x=>`<option value="${x[0]}"${F[n]==x[0]?" selected":""}>${x[1]}</option>`).join("")}</select>`;
const subs=k=="roupas"?["Blusas","Calças","Vestidos","Saias","Conjuntos","Blazers"]:k=="acessorios"?ACC:[];
const items=list(k,sub);
return `<div class="w" style="padding-top:48px"><h1 style="font-size:clamp(36px,5vw,64px)">${I[0]}${sub?" · "+(sub.charAt(0).toUpperCase()+sub.slice(1)):""}</h1><p style="color:var(--mut);max-width:52ch">${I[1]}</p>
${subs.length?`<nav class="sn" aria-label="Subcategorias" style="margin-top:24px">${subs.map(s=>`<a href="#/c/${k}/${slug(s)}" class="${sub==slug(s)?"on":""}">${s.toUpperCase()}</a>`).join("")}<a href="#/c/${k}" class="${sub?"":"on"}">VER TUDO</a></nav>`:""}
<div class="bar">${sel("tam","Tamanho",ALLT.map(x=>[x,x]))}${sel("cor","Cor",ALLC.map(c=>[c,CL[c][0]]))}${sel("pr","Preço",[["0-130","Até R$ 130"],["130-200","R$ 130–200"],["200-500","Acima de R$ 200"]])}${sel("est","Estilo",["Casual","Office","Night","Weekend"].map(x=>[x,x]))}<label><input type="checkbox" data-f="disp"${F.disp?" checked":""} style="min-height:0"> Em estoque</label><span style="flex:1"></span>${sel("o","Ordenar",[["n","Mais recentes"],["b","Mais vendidos"],["lo","Menor preço"],["hi","Maior preço"]])}</div>
<p style="color:var(--mut);font-size:13px">${items.length} ${items.length==1?"peça":"peças"}</p>
<div class="grid" style="margin-bottom:96px">${items.map(card).join("")||'<p>Nenhuma peça por aqui ainda. Volte em breve ou veja a coleção completa.</p>'}</div></div>`};
V.pdp=s=>{const p=PRODS.find(x=>x.slug==s);if(!p)return V.home();const v=S.V;if(v.id!=p.id)S.V=Object.assign(v,{id:p.id,tam:sz(p,p.cores[0]),cor:p.cores[0],q:1,img:0});
const rel=PRODS.filter(x=>x.id!=p.id&&(x.sub==p.sub||x.cat==p.cat)).slice(0,4);
return `<div class="w"><div class="pdp"><div class="gal"><div class="th">${[0,1,2,3].map(i=>`<button data-img="${i}" aria-current="${S.V.img==i}" aria-label="Foto ${i+1}">${ph(p,i)}</button>`).join("")}</div><div class="main" id="main" data-a="zoom">${S.V.img==3?`<div class="ph" style="--a:#3B3936;--z:#1E1D1B"><span style="color:#F7F5F1">Vídeo do produto (placeholder)</span></div>`:ph(p,S.V.img)}</div></div>
<div class="info"><small style="letter-spacing:.14em">${p.sub.toUpperCase()}</small><h1>${p.nome}</h1><div class="pr">${p.de?`<s style="color:var(--mut);font-size:16px">${brl(p.de)}</s> `:""}${brl(p.preco)}</div><small style="color:var(--mut)">Pix sem acréscimo · ${inst(p.preco)}</small>
<p class="lbl" style="margin-top:24px">COR: ${CL[S.V.cor][0].toUpperCase()}</p><div class="opt">${p.cores.map(c=>`<button class="cs" data-cor="${c}" aria-pressed="${S.V.cor==c}" aria-label="${CL[c][0]}" style="background:${CL[c][1]}"></button>`).join("")}</div>
<p class="lbl">TAMANHO <a href="#" data-a="guide" style="text-decoration:underline;margin-left:12px;letter-spacing:0">Guia de tamanhos</a></p><div class="opt">${p.tam.map(t=>`<button data-tam="${t}" aria-pressed="${S.V.tam==t}"${p.v.some(x=>x[0]==S.V.cor&&x[1]==t)?"":" disabled"}>${t}</button>`).join("")}</div><div class="er" id="te"></div>
<p class="lbl">QUANTIDADE</p><div class="qty" style="margin:8px 0 20px"><button data-vq="-1" aria-label="Diminuir">−</button><span>${S.V.q}</span><button data-vq="1" aria-label="Aumentar">+</button></div>
<div style="display:flex;gap:8px"><button class="btn" style="flex:1" data-add="${p.id}">ADICIONAR À SACOLA</button>${fh(p.id).replace('class="fav"','class="fav" style="position:static;border:1px solid var(--ln);width:52px"')}</div>
<div style="margin-top:32px">${[["DESCRIÇÃO",p.desc],["COMPOSIÇÃO",p.det?`Tecido: ${p.det}.`:"Sob consulta no atendimento."],["DETALHES",`Tamanhos da peça: ${p.tam.join(", ")}.`],["CUIDADOS","Siga as instruções da etiqueta da peça."],["ENTREGA","Entrega exclusivamente por aplicativo, mediante consulta. O valor é de responsabilidade da cliente e informado no momento da compra. A retirada também é possível."],["TROCAS E DEVOLUÇÕES","Em até 7 dias, com a etiqueta fixada na peça e mediante disponibilidade de estoque. Solicite pelo nosso atendimento."]].map(([t,c])=>`<details><summary>${t}</summary><p>${c}</p></details>`).join("")}</div></div></div>
<h2 style="margin-bottom:24px">Você também pode gostar</h2><div class="grid" style="margin-bottom:96px">${rel.map(card).join("")}</div></div>`};
V.fav=()=>`<div class="w" style="padding-top:48px"><h1 style="font-size:clamp(36px,5vw,64px)">Meus favoritos</h1><div class="grid" style="margin:32px 0 96px">${S.fav.map(by).filter(Boolean).map(card).join("")||'<p style="color:var(--mut)">Toque no coração de uma peça para salvá-la aqui.</p>'}</div></div>`;
const fld=(n,l,ph_="",cl="",t="text")=>`<label class="${cl}">${l}<input name="${n}" type="${t}" placeholder="${ph_}" value="${S.ck[n]||""}" autocomplete="on"></label>`;
V.conta=()=>{const m=S.acc||"login";if(S.user)return `<div class="pg"><h1>Minha conta</h1><p>Olá, ${S.user.n}.</p><div style="display:grid;gap:8px;margin:24px 0">${["Meus pedidos","Dados pessoais","Endereços","Senha"].map(t=>`<details><summary>${t.toUpperCase()}</summary><p>Área ligada ao backend de clientes (a implementar).</p></details>`).join("")}<a href="#/favoritos" style="padding:14px 0;border-top:1px solid var(--ln);letter-spacing:.14em;font-size:13px">FAVORITOS (${S.fav.length})</a></div><button class="btn o" data-a="logout">SAIR</button></div>`;
return `<div class="pg" style="max-width:460px"><h1 style="font-size:44px">${m=="cad"?"Cadastro":m=="esq"?"Esqueci minha senha":"Entrar"}</h1><form data-form="${m}" class="fg" style="grid-template-columns:1fr">${m=="cad"?fld("n","Nome"):""}${fld("e","E-mail","","","email")}${m!="esq"?fld("s","Senha","","","password"):""}<div class="er" id="fe"></div><button class="btn">${m=="cad"?"CRIAR CONTA":m=="esq"?"ENVIAR LINK":"ENTRAR"}</button></form><p style="margin-top:20px;font-size:14px">${m!="login"?'<a href="#" data-acc="login" style="text-decoration:underline">Entrar</a> · ':""}${m!="cad"?'<a href="#" data-acc="cad" style="text-decoration:underline">Criar conta</a> · ':""}${m!="esq"?'<a href="#" data-acc="esq" style="text-decoration:underline">Esqueci minha senha</a>':""}</p></div>`};
V.sobre=()=>`<div class="about"><h1>TRAMISSE</h1><h2>Threads of Identity</h2></div><div class="w" style="padding-bottom:40px"><div class="tiles" style="grid-template-columns:1fr 1fr;margin:80px 0">${tile("",'#/',3,"brand")}${tile("",'#/',5,"cover")}</div><div class="pg"><p style="font:italic 26px/1.4 var(--serif)">A Tramisse nasceu em Belém para vestir mulheres que sabem quem são. Fios de identidade, tecidos em peças essenciais e atemporais.</p><p>Texto institucional de exemplo: substitua pela história real da marca.</p></div></div>`;
const PG={faq:["Como comprar","<b>Pagamento</b><br>Pix. Cartão de débito com acréscimo de 5%. Cartão de crédito em até 2x, com acréscimo de 5%.<br><br><b>Entregas</b><br>Realizadas exclusivamente por aplicativo, mediante consulta. O valor da entrega é de responsabilidade da cliente e informado no momento da compra.<br><br><b>Retirada</b><br>Também é possível retirar. O endereço é disponibilizado após a confirmação da compra."],trocas:["Trocas e devoluções","As trocas devem ser realizadas em até 7 dias, com etiqueta fixada na peça, mediante disponibilidade do estoque. A troca deve ser solicitada pelo nosso atendimento."],contato:["Contato","Atendimento pelo WhatsApp:<br><a href='https://wa.me/5591999654699' style='text-decoration:underline'>(91) 99965-4699 — Giovana</a><br><a href='https://wa.me/5591999631582' style='text-decoration:underline'>(91) 99963-1582 — Victoria</a><br><br>Instagram: <a href='https://instagram.com/tramissebrasil' style='text-decoration:underline'>@tramissebrasil</a>"],privacidade:["Política de privacidade","Texto legal a ser fornecido. Descreva quais dados são coletados, por quê e como solicitar a exclusão (LGPD)."],termos:["Termos de uso","Texto legal a ser fornecido."]};
V.pg=k=>{const[t,c]=PG[k]||PG.faq;return `<div class="pg"><h1>${t}</h1><p>${c}</p></div>`};
const ordMsg=()=>{const t=tot(),c=S.ck;return "Olá! Quero finalizar um pedido na Tramisse:\n\n"+S.bag.map(l=>`• ${by(l.id).nome} — ${CL[l.cor][0]}, tam. ${l.tam}, ${l.q}x — ${brl(by(l.id).preco*l.q)}`).join("\n")+`\n\nSubtotal: ${brl(t.sub)}`+(t.d?`\nDesconto (${S.cp}): -${brl(t.d)}`:"")+(t.acr?`\nAcréscimo do cartão (5%): ${brl(t.acr)}`:"")+`\nTotal (sem entrega): ${brl(t.sub-t.d+t.acr)}\nPagamento: ${{pix:"Pix",db:"Cartão de débito",cc:"Cartão de crédito (até 2x)"}[S.pay]}\n`+(S.ship==1?"Retirada":`Entrega por aplicativo: ${[c.end,c.num,c.cmp,c.bai,c.cid,c.uf,c.cep].filter(Boolean).join(", ")} (destinatário: ${c.dest})`)+`\n\nCliente: ${c.n} ${c.sn} · ${c.tel} · ${c.e}`};
V.ck=()=>{if(S.step==4&&S.bag.length)S.step=0;const t=tot(),total=t.sub-t.d+t.acr,names=["SACOLA","IDENTIFICAÇÃO","ENTREGA","PAGAMENTO"];
if(S.step==4)return `<div class="pg"><h1>Pedido enviado</h1><p>Abrimos o WhatsApp da ${S.at} com o resumo do seu pedido. Confirme o envio por lá: o atendimento combina pagamento e entrega ou retirada com você.</p><p><a class="btn" href="${S.wa}" target="_blank" rel="noopener">ABRIR WHATSAPP</a> <a class="btn o" href="#/">VOLTAR À HOME</a></p></div>`;
if(!S.bag.length)return `<div class="pg"><h1>Sacola vazia</h1><a class="btn" href="#/c/new-in">VER NEW IN</a></div>`;
const sum=`<details open class="sm"><summary style="font-size:15px">RESUMO DO PEDIDO · ${brl(total)}</summary>${S.bag.map(l=>{const p=by(l.id);return `<div class="ln"><div class="im">${ph(p,0)}</div><div>${p.nome}<br><small>${CL[l.cor][0]} · ${l.tam} · ${l.q}x</small><br>${brl(p.preco*l.q)}</div></div>`}).join("")}<div class="tt"><span>Subtotal</span><span>${brl(t.sub)}</span></div><div class="tt"><span>Entrega</span><span>${S.ship==1?"Retirada":"Por aplicativo"}</span></div>${t.d?`<div class="tt"><span>Desconto</span><span>-${brl(t.d)}</span></div>`:""}${t.acr?`<div class="tt"><span>Acréscimo do cartão (5%)</span><span>${brl(t.acr)}</span></div>`:""}<div class="tt big"><span>Total</span><span>${brl(total)}</span></div><small style="color:var(--mut)">O valor da entrega por aplicativo é informado no atendimento.</small></details>`;
let f="";
if(S.step==0)f=`<h2>Sacola</h2><div style="margin:16px 0">${S.bag.map(l=>by(l.id).nome+" · "+l.q+"x").join("<br>")}</div><button class="btn" data-go="1">CONTINUAR</button>`;
if(S.step==1)f=`<h2>Identificação</h2><form data-form="id" class="fg" style="margin-top:16px">${fld("e","E-mail","","s","email")}${fld("n","Nome")}${fld("sn","Sobrenome")}${fld("tel","Telefone","(91) 90000-0000")}${fld("cpf","CPF (opcional)","000.000.000-00")}<div class="er s" id="fe"></div><button class="btn s">IR PARA A ENTREGA</button></form>`;
if(S.step==2)f=`<h2>Entrega</h2><form data-form="en" class="fg" style="margin-top:16px"><div class="s"><label class="opc"><input type="radio" name="sh" value="0"${S.ship!=1?" checked":""}><span>Entrega por aplicativo<br><small>Valor informado no momento da compra, por conta da cliente.</small></span></label><label class="opc"><input type="radio" name="sh" value="1"${S.ship==1?" checked":""}><span>Retirada<br><small>O endereço é enviado após a confirmação da compra.</small></span></label></div>${S.ship==1?"":fld("cep","CEP","00000-000")+fld("end","Endereço")+fld("num","Número")+fld("cmp","Complemento")+fld("bai","Bairro")+fld("cid","Cidade")+fld("uf","Estado")+fld("dest","Destinatário","","s")}<div class="er s" id="fe"></div><button class="btn s">IR PARA O PAGAMENTO</button></form>`;
if(S.step==3)f=`<h2>Pagamento</h2><form data-form="pg" class="fg" style="margin-top:16px"><div class="s">${[["pix","Pix","Sem acréscimo."],["db","Cartão de débito","Acréscimo de 5%."],["cc","Cartão de crédito","Até 2x, com acréscimo de 5%."]].map(o=>`<label class="opc"><input type="radio" name="pay" value="${o[0]}"${S.pay==o[0]?" checked":""}><span>${o[1]}<br><small>${o[2]}</small></span></label>`).join("")}</div><label class="s">Quem vai te atender<select name="at">${CFG.wa.map(a=>`<option>${a[0]}</option>`).join("")}</select></label><p class="s" style="color:var(--mut);font-size:14px">Você envia o pedido pelo WhatsApp e o atendimento confirma o pagamento e a entrega. Nenhum dado de cartão é coletado neste site.</p><div class="er s" id="fe"></div><button class="btn s">ENVIAR PEDIDO PELO WHATSAPP</button></form>`;
return `<div class="w"><div style="padding-top:32px;display:grid;justify-items:center"><a class="logo" href="#/" aria-label="Tramisse">TRAMISSE</a></div><div class="steps" style="margin-top:24px">${names.map((n,i)=>`<span class="${i<=S.step?"on":""}">${n}</span>`).join("")}</div><div class="ck"><div>${f}${S.step>0?`<p><a href="#" data-go="${S.step-1}" style="text-decoration:underline;font-size:14px">← Voltar</a></p>`:""}</div><div>${sum}</div></div></div>`};
/* ===== ROUTER ===== */
const META={};function meta(t,d){document.title=t+" — Tramisse";$('meta[name=description]').content=d||"Tramisse, moda feminina brasileira contemporânea."}
function route(){const h=location.hash.replace(/^#\/?/,""),[a,b,c]=h.split("/"),app=$("#app");let out,t="Threads of Identity";
if(!a)out=V.home();else if(a=="c"){out=V.cat(b||"todos",c);t=(INFO[b]||INFO.todos)[0]}else if(a=="p"){out=V.pdp(b);const p=PRODS.find(x=>x.slug==b);if(p)t=p.nome}else if(a=="favoritos"){out=V.fav();t="Favoritos"}else if(a=="conta"){out=V.conta();t="Minha conta"}else if(a=="checkout"){out=V.ck();t="Checkout"}else if(a=="sobre"){out=V.sobre();t="Sobre"}else if(a=="pagina"){out=V.pg(b);t=(PG[b]||PG.faq)[0]}else out=V.home();
app.innerHTML=out;meta(t,a=="p"&&b?(PRODS.find(x=>x.slug==b)||{}).desc:"");dr();document.body.classList.toggle("home",!a);scrollTo(0,0);counts();bag();sc();reels()}
function sc(){const y=scrollY,tb=$("#top").offsetHeight;document.documentElement.style.setProperty("--ty",Math.max(0,tb-y)+"px");document.body.classList.toggle("sol",!document.body.classList.contains("home")||y>60)}
addEventListener("scroll",sc,{passive:true});addEventListener("resize",sc);
function reels(){clearInterval(window.rt);const rc=$("#c3");$$("video[data-rv]").forEach(v=>vio.observe(v));if(rc&&!matchMedia("(prefers-reduced-motion:reduce)").matches)window.rt=setInterval(()=>{if(rc.matches(":hover"))return;const end=rc.scrollLeft+rc.clientWidth>=rc.scrollWidth-4;rc.scrollTo({left:end?0:rc.scrollLeft+rc.clientWidth*.5,behavior:"smooth"})},3800)}
function again(){const y=scrollY;route();scrollTo(0,y)}
addEventListener("hashchange",route);
/* ===== EVENTOS ===== */
document.addEventListener("click",e=>{const t=e.target.closest("button,a,[data-a],[data-fav],[data-img],[data-cor],[data-tam]");if(!t)return;const d=t.dataset;
if(d.a=="menu")dr("m");else if(d.a=="bag"){dr("g");bag()}else if(d.a=="close")dr();
else if(d.a=="search"){const q=prompt("Buscar na Tramisse");if(q){const l=PRODS.filter(p=>(p.nome+p.sub+p.tags).toLowerCase().includes(q.toLowerCase()));$("#app").innerHTML=`<div class="w" style="padding-top:48px"><h1>Busca: ${q.replace(/</g,"")}</h1><div class="grid" style="margin:32px 0 96px">${l.map(card).join("")||"<p>Nada encontrado.</p>"}</div></div>`}}
else if(d.a=="guide"){e.preventDefault();$("#modc").innerHTML=`<h3>Guia de tamanhos</h3><table><tr><th>Tam.</th><th>Busto</th><th>Cintura</th><th>Quadril</th></tr>${[["PP",84,66,90],["P",88,70,94],["M",92,74,98],["G",98,80,104],["GG",104,86,110]].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</table><small>Medidas de exemplo em cm.</small><br><br><button class="btn o" data-a="mc">FECHAR</button>`;$("#mod").classList.add("on")}
else if(d.a=="mc")$("#mod").classList.remove("on");
else if(d.a=="coupon"){const c=$("#cpi").value.trim().toUpperCase();if(CFG.coupons[c]){S.cp=c;bag()}else $("#cpe").textContent="Código inválido. Confira e tente de novo."}
else if(d.a=="logout"){S.user=null;save();again()}
else if(d.a=="zoom"){$("#main").classList.toggle("z")}
if(d.fav){e.preventDefault();e.stopPropagation();const id=+d.fav;S.fav=S.fav.includes(id)?S.fav.filter(x=>x!=id):[...S.fav,id];save();$$(`[data-fav="${id}"]`).forEach(b=>b.setAttribute("aria-pressed",S.fav.includes(id)));counts()}
if(d.car){const c=$("#"+d.car);c.scrollBy({left:c.clientWidth*.8*d.d,behavior:"smooth"})}
if(d.img!=null&&d.img!==""&&t.hasAttribute("data-img")){S.V.img=+d.img;again()}
if(d.cor){const pp=PRODS.find(x=>x.id==S.V.id);S.V.cor=d.cor;S.V.tam=sz(pp,d.cor);again()}if(d.tam){S.V.tam=d.tam;again()}if(d.vq){S.V.q=Math.max(1,S.V.q+ +d.vq);again()}
if(d.add){const p=by(d.add);if(!S.V.tam){$("#te").textContent="Escolha um tamanho para continuar.";return}const k=S.bag.find(l=>l.id==p.id&&l.tam==S.V.tam&&l.cor==S.V.cor);k?k.q+=S.V.q:S.bag.push({id:p.id,tam:S.V.tam,cor:S.V.cor,q:S.V.q});save();bag();dr("g")}
if(d.q!=null&&t.hasAttribute("data-q")){const l=S.bag[+d.q];l.q+=+d.d;if(l.q<1)S.bag.splice(+d.q,1);save();bag()}
if(d.rm!=null){S.bag.splice(+d.rm,1);save();bag()}
if(d.acc){e.preventDefault();S.acc=d.acc;again()}
if(d.go!=null){e.preventDefault();S.step=+d.go;again()}});
document.addEventListener("mousemove",e=>{const m=e.target.closest&&e.target.closest("#main.z");if(m){const r=m.getBoundingClientRect();m.style.setProperty("--ox",(e.clientX-r.left)/r.width*100+"%");m.style.setProperty("--oy",(e.clientY-r.top)/r.height*100+"%")}});
document.addEventListener("change",e=>{const t=e.target;if(t.dataset.f){S.F[t.dataset.f]=t.type=="checkbox"?t.checked:t.value;again()}
if(t.name=="pay"){S.pay=t.value;again()}if(t.name=="sh"){S.ship=+t.value;Object.assign(S.ck,Object.fromEntries(new FormData(t.form)));again()}});
document.addEventListener("keydown",e=>{if(e.key=="Escape"){dr();$("#mod").classList.remove("on")}});
document.addEventListener("submit",e=>{const f=e.target.closest("form[data-form]");if(!f)return;e.preventDefault();const k=f.dataset.form,fd=Object.fromEntries(new FormData(f)),er=$("#fe")||$("#nle"),bad=(m,names)=>{er.textContent=m;$$("input",f).forEach(i=>i.classList.toggle("bad",names.includes(i.name)&&!i.value.trim()));return 0};
const miss=n=>n.filter(x=>!(fd[x]||"").trim());
if(k=="nl"){if(!/^\S+@\S+\.\S+$/.test(fd.e))return void(er.textContent="Digite um e-mail válido.");er.innerHTML='<span class="okk">Cadastro feito. Até logo!</span>';f.reset();return}
if(k=="login"||k=="cad"||k=="esq"){if(!/^\S+@\S+\.\S+$/.test(fd.e||""))return void(er.textContent="Digite um e-mail válido.");if(k=="esq"){er.innerHTML='<span class="okk">Enviamos o link para o seu e-mail (demonstração).</span>';return}if(!fd.s)return void(er.textContent="Digite sua senha.");S.user={n:fd.n||fd.e.split("@")[0],e:fd.e};save();again();return}
Object.assign(S.ck,fd);
if(k=="id"){const m=miss(["e","n","sn","tel"]);if(m.length)return bad("Preencha os campos obrigatórios.",m);S.step=2;again()}
if(k=="en"){if(S.ship!=1){const m=miss(["cep","end","num","bai","cid","uf","dest"]);if(m.length)return bad("Preencha os campos obrigatórios.",m)}S.step=3;again()}
if(k=="pg"){S.at=fd.at;const w=CFG.wa.find(a=>a[0]==S.at)[1];S.wa="https://wa.me/"+w+"?text="+encodeURIComponent(ordMsg());S.bag=[];S.cp=null;S.step=4;save();again();window.open(S.wa,"_blank")}});
shell();route();
